apiVersion: apps/v1
kind: Deployment
metadata: 
  name: apache2
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: apache2
  template: 
    metadata: 
      labels: 
        app: apache2
    spec: 
      containers: 
        - 
          image: "nambisankaran/devopslabel:apache2image"
          imagePullPolicy: Always
          name: apache2
          ports: 
            - 
              containerPort: 80
              protocol: TCP
          resources: 
            limits: 
              cpu: 250m
              memory: 256Mi
            requests: 
              cpu: 250m
              memory: 256Mi
          volumeMounts:
          - name: apache2
            mountPath: /home/ubuntu/apache2pv
      volumes:
      - name: apache2
        persistentVolumeClaim:
            claimName: apache2
